# Generated by Django 5.1 on 2024-09-30 09:59

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('brief', models.CharField(max_length=300)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='article/')),
                ('slug', models.SlugField(unique=True)),
                ('author', models.CharField(max_length=100)),
                ('views', models.IntegerField(default=0)),
                ('author_profile_picture', models.ImageField(blank=True, null=True, upload_to='author_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='events/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EventVolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('preferred_contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email')], max_length=10)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_relationship', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('areas_of_interest', multiselectfield.db.fields.MultiSelectField(choices=[('SGBV/CEFM', 'SGBV/CEFM'), ('Legal and Correctional Centre Apostolate', 'Legal and Correctional Centre Apostolate'), ('Micro Credit', 'Micro Credit'), ('Environment and Climate Change', 'Environment and Climate Change'), ('Human Rights', 'Human Rights'), ('Livelihood Support', 'Livelihood Support'), ('Health', 'Health'), ('Good Governance', 'Good Governance')], max_length=255)),
                ('have_volunteered_before', models.TextField(blank=True, null=True)),
                ('why_interested_in_volunteering', models.TextField()),
                ('volunteer_position_preferences', models.TextField()),
                ('available_hours_days', models.CharField(max_length=255)),
                ('relevant_training_experience_skills', models.TextField()),
                ('affiliated_organizations', models.TextField(blank=True, null=True)),
                ('current_employer', models.CharField(blank=True, max_length=255, null=True)),
                ('highest_education_level', models.CharField(blank=True, max_length=255, null=True)),
                ('prior_criminal_convictions', models.TextField(blank=True, null=True)),
                ('physical_limitations', models.TextField(blank=True, null=True)),
                ('reference_one_name', models.CharField(max_length=255)),
                ('reference_one_phone', models.CharField(max_length=15)),
                ('reference_one_relationship', models.CharField(max_length=255)),
                ('reference_two_name', models.CharField(max_length=255)),
                ('reference_two_phone', models.CharField(max_length=15)),
                ('reference_two_relationship', models.CharField(max_length=255)),
                ('t_shirt_size', models.CharField(max_length=10)),
                ('how_heard_about_us', models.TextField()),
                ('acknowledgment', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('brief', models.TextField()),
                ('volume', models.IntegerField()),
                ('number', models.IntegerField()),
                ('edition', models.CharField(max_length=60)),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='newsletter-images/')),
                ('newsletter', models.FileField(upload_to='newsletters/')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='programs/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledgment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Events.gallery')),
            ],
        ),
    ]
